# Generated by Django 5.2.12 on 2026-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_game_name_transaction_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('GAME', 'Top Up Game'), ('PULSA', 'Pulsa & Paket Data'), ('EWALLET', 'E-Wallet (Dana, OVO, dll)')], default='GAME', max_length=20),
        ),
    ]
